### ISSUE TITLE
Usunięcie script.mtvguide

### ISSUE THREAD

**Issue by Mariusz89B** [MultiWu/build#2]
Witam,

Proszę o usunięcie wtyczki script.mtvguide z kodu źródłowego "build/addons/". Wtyczka narusza prawa autorskie oraz regulamin githuba, a także zawiera moje imię bez zgody.

Pozdr.
Mariusz

**Comment by MultiWu** [comment]
Zgodnie z licencją m-TVGuide KODI Addon, mogę go rozprzestrzeniać i dowolnie edytować.
Program zawiera twoje imie jako autora.
